bcgov/foi-docreviewer

.github/workflows/api-cd.yml, .github/workflows/web-cd.yml, api/reviewer_api/models/DocumentPathMapper.py, api/reviewer_api/resources/foiflowmasterdata.py, api/reviewer_api/services/radactionservice.py, openshift/templates/api-build.yaml, openshift/templates/web-build.yaml, web/src/apiManager/services/foiOSSService.tsx, web/src/components/FOI/Home/Home.tsx, web/src/components/FOI/Home/Redlining.js
1. get s3 creds from mapper
2. openshift build is against dev branch now
3. github action is against dev branch now
=> Fetch document from s3

api/migrations/versions/92764562d406_.py, api/migrations/versions/a6eaec196523_.py, api/migrations/versions/b96f3a390985_.py, api/reviewer_api/models/Annotations.py, api/reviewer_api/models/DocumentDeleted.py, api/reviewer_api/models/DocumentHashCodes.py, api/reviewer_api/models/Documents.py, api/reviewer_api/resources/__init__.py, api/reviewer_api/resources/documentdelete.py, api/reviewer_api/services/documentservice.py
=> record delete

api/reviewer_api/models/Documents.py, computingservices/DedupeServices/services/dedupedbservice.py
or deleting a duplicate from another division
=> fix edge case with deleting original with multiple divisions

api/reviewer_api/models/Documents.py
to filter out duplicates and aggregate divisions 
refactor subquery to helper function
=> update get documents query for displaying on reviewer app left panel

.github/workflows/zap-scan.yml
This must be merged into the main branch in order for the nightly scheduling to work.
=> 1398 - ZAP Scan automation

api/reviewer_api/models/Documents.py
Reverts bcgov/foi-docreviewer#58
=> Revert "Dev nk 3293"

web/src/components/FOI/Home/Redlining.js
change all section id to type number to reduce bugs fix edit save parent annotation name bug
=> fix switching between documents too fast bug

.gitignore, api/migrations/versions/3d6b76fc4f9d_encryped_s3_buckets.py, api/migrations/versions/cb81f7d5bfca_.py, computingservices/DedupeServices/services/s3documentservice.py
Update s3 path in db to encrypted buckets
=> Dev rq 3393

api/migrations/versions/48191befb823_.py, api/reviewer_api/models/AnnotationSections.py, api/reviewer_api/services/annotationservice.py, web/src/components/FOI/Home/Redlining.js
fix section ordering
fix blank code section in migration script
=> fix save code not disabled after second modal open

.gitignore, api/migrations/versions/3d6b76fc4f9d_encryped_s3_buckets.py, computingservices/DedupeServices/services/s3documentservice.py, web/src/components/FOI/Home/Redlining.js
Reverts bcgov/foi-docreviewer#87
=> Revert "Revert "fix delete section annotation when redact all""

computingservices/PDFStitchServices/services/pdfstichservice.py, computingservices/PDFStitchServices/services/s3documentservice.py
only merge pdf files
non pdf files will be included in zip archive
=> add zip functionality

web/src/components/FOI/Home/DocumentSelector.scss, web/src/components/FOI/Home/DocumentSelector.tsx
Margin & document selection Fix
=> Margin & document selection Fix

api/reviewer_api/services/documentpageflagservice.py, api/reviewer_api/services/documentservice.py, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/Home.js
Removed debug statements in FE.
Fixed variable declaration in BE.
=> Small Fixes

MCS.FOI.S3FileConversion/Docker.bcgov, MCS.FOI.S3FileConversion/Dockerfile, MCS.FOI.S3FileConversion/Dockerfile.local, MCS.FOI.S3FileConversion/MCS.FOI.CalendarToPDF/CalendarFileProcessor.cs, MCS.FOI.S3FileConversion/MCS.FOI.DocToPDF/DocFileProcessor.cs, MCS.FOI.S3FileConversion/MCS.FOI.ExcelToPDF/ExcelFileProcessor.cs, MCS.FOI.S3FileConversion/MCS.FOI.S3FileConversion/S3Handler.cs, computingservices/DedupeServices/services/dedupedbservice.py
=> add fonts + error handling to conversion service, minor bug fix for redaction ready status

computingservices/DedupeServices/rstreamio/redisstreamwriter.py, computingservices/DedupeServices/services/dedupedbservice.py, computingservices/DedupeServices/services/dedupeservice.py, computingservices/DedupeServices/services/foiredisdedupeconsumer.py
@nkan-aot , @sumathi-thirumani-aot , @aparna-aot , @richard-aot , @divyav-aot : As discussed, this PR will be merged by myself, but you folks can review my updates before its merges to Main Branch
=> #3560 Dedupe DB Service code updates, exceptions handling!

MCS.FOI.S3FileConversion/MCS.FOI.S3FileConversion/S3Handler.cs, api/reviewer_api/resources/foiflowmasterdata.py, api/reviewer_api/services/jobrecordservice.py, computingservices/DedupeServices/services/s3documentservice.py, computingservices/PDFStitchServices/services/blobpdfstitchservice.py, computingservices/PDFStitchServices/services/pdfstichservice.py
Extensions - Lowercase check added
=> Extensions - Lowercase check added

api/reviewer_api/services/documentservice.py
duplicatemaster_attachments is none
=> handle the case that

computingservices/PDFStitchServices/services/pdfstichservice.py
Fix - Data loss happens for fillable pdfs during pdf stiching#3835.
=> Data loss happens for fillable pdfs during pdf stiching#3835

web/src/components/FOI/Home/Redlining.js
Fix for missing code for fetching annotations for first document
=> Fix for missing code for fetching annotations for first document

web/src/components/FOI/Home/Redlining.js
Removed color picker and formatter popup while doing redaction.
Added removed code while merging PR.
=> Colour Picker Always Opens on New Redaction #3581

api/reviewer_api/services/documentservice.py, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/Redlining.js, web/src/constants/enum.ts
add enum for page flag types
add back in overwritten code for mutually exclusive blank code
=> in progress flag for blank code redaction

web/src/components/FOI/Home/Redlining.js
image files not being stitched properly, so manually insert a page, then load image onto page
=> fix page front end stitching bug with image files

web/src/components/FOI/Home/DocumentSelector.tsx
Unit Testing
Create a Request
State Transition
Upload Records
Apply page flag.
=> 4179 icon changes.

api/reviewer_api/models/DocumentMaster.py, web/src/components/FOI/Home/Redlining.js
1. sort doc by lastmodified on server side
2. bug fix: saving redline - remove dup/non-resp pages issue
=> Bug fixes for saving redline

api/reviewer_api/models/Annotations.py, api/reviewer_api/resources/redaction.py, api/reviewer_api/services/annotationservice.py, api/reviewer_api/services/radactionservice.py, web/src/apiManager/services/docReviewerService.tsx, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/Home.js, web/src/components/FOI/Home/Redlining.js, web/src/components/FOI/Home/utils.js
fix bug with multi full page redaction saving with the same docid
=> always sort in the same order for front end stitching

api/reviewer_api/resources/redaction.py, api/reviewer_api/services/radactionservice.py, web/src/apiManager/services/docReviewerService.tsx, web/src/components/FOI/Home/Redlining.js
Ignore annots/redact changes from applyRedaction
=> Dev marshal rq 3231

web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/DocumentSelector.scss, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/utils.js
=> Filter by Consultee#4133

web/src/components/FOI/Home/DocumentSelector.tsx
=> Minor Popup style update related to positioning

web/src/components/FOI/Home/DocumentSelector.tsx
Updates related to Filter By consultee which is already pushed to test-marshal.
=> Updates related to Filter By consultee already pushed to test-marshal

api/reviewer_api/models/AnnotationSections.py, api/reviewer_api/models/Annotations.py, api/reviewer_api/models/DocumentMaster.py, api/reviewer_api/services/annotationservice.py, api/reviewer_api/services/documentservice.py, web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/Redlining.js
invalid ministry id passed during edit call
doc version hardcoded as 1
multiple annotation calls triggered by grouping annotation
=> fix duplicate calls for page flags,

api/reviewer_api/models/DocumentPageflags.py, web/src/components/FOI/Home/Redlining.js
do not save changes triggered by saving redline
=> fix bug created by previous commit

api/reviewer_api/services/external/zipperproducerservice.py
merging as it is only print statements for debugging the issue.
=> debug line added

api/reviewer_api/models/AnnotationSections.py, api/reviewer_api/models/Annotations.py, api/reviewer_api/services/annotationservice.py, api/reviewer_api/services/radactionservice.py, api/reviewer_api/utils/util.py, api/sample.env, docker-compose.yml
Unit Testing
1. Create a request
2. Upload Records
3. Single Annotation Save
4. Single Annotation Update
5. Multiple Annotation Save
6. Multiple Annotation Update
=> Dev marshal st 4351

web/src/components/FOI/Home/Redlining.js
**Description:** 
Fix for Blank Code - Entering Comment/Reply in Comments Tab Adds it as FOIPPA Section Stamp Text#4372
=> Fix for Blank Code - Entering Comment/Reply in Comments Tab Adds it as FOIPPA Section Stamp Text#4372

web/public/stylesheets/webviewer.css, web/src/components/FOI/Home/Redlining.js
All fixes related to Find and Redact - #4386,#4385 and #4378
=> All fixes related to Find and Redact - #4386,#4385 and #4378

api/reviewer_api/models/RedactionLayers.py, web/src/components/FOI/Home/Redlining.js
fix redaction layer count query to exclude deleted documents
=> fix foippa section modal not clearing when editing redaction

web/src/components/FOI/App.scss, web/src/components/FOI/Home/Redlining.js
- 'Save as default ' button is enabled even if no FOIPPA section is selected#4324
- Disable automated legal search term#4415
=> PR - #4324 & #4415

web/src/components/FOI/Home/Redlining.js
Redactions not applied in Response Package#4512
=> Redactions not applied in Response Package#4512

api/reviewer_api/models/AnnotationSections.py, api/reviewer_api/models/Annotations.py, api/reviewer_api/models/RedactionLayers.py, web/src/apiManager/services/docReviewerService.tsx, web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/Redlining.js
1. Subqueries added with alias
2. warnings related to setCustomData()
3. console warning fixes related to getBoundingClientRect()
4. Error message updated for pdftron license GET
=> changes related to Patroni logs and console warnings

web/src/apiManager/services/docReviewerService.tsx, web/src/components/FOI/Home/Redlining.js
Changes to include error toast and removal of deprecated snippets.
=> Include error modal for api failure.

computingservices/ZippingServices/services/foirediszipperconsumer.py, computingservices/ZippingServices/services/zipperservice.py
Reverts bcgov/foi-docreviewer#532
=> Revert "#4510 Trial code - Zipper restart code"

computingservices/ZippingServices/services/foirediszipperconsumer.py
Reverts bcgov/foi-docreviewer#531
=> Revert "#4510 - TEST CODE, commented code block!"

api/reviewer_api/services/documentpageflagservice.py, api/reviewer_api/services/radactionservice.py, web/src/components/FOI/Home/Redlining.js
=> WebViewer constructor with disableVirtualDisplayMode: true

api/reviewer_api/resources/document.py, api/reviewer_api/resources/documentpageflag.py, api/reviewer_api/resources/jobstatus.py, api/reviewer_api/resources/pdfstitchpackage.py, api/reviewer_api/resources/redaction.py, api/reviewer_api/tracer.py, computingservices/PDFStitchServices/services/pdfstichservice.py
Python 3 exceptions do not have a message attributes. See [PEP 352](https://www.python.org/dev/peps/pep-0352/) for more details.
Please see corresponding foi-flow PR here: https://github.com/bcgov/foi-flow/pull/4608
=> Ticket 4539. Fix/Adjustment to exception handling in reviewer api

web/src/components/FOI/Home/Redlining.js
Changes to handle the usecase of ignoring a document where all pages are flagged not responsive or duplicate.
=> Test marshal st 4514 v1

MCS.FOI.S3FileConversion/MCS.FOI.MSGToPDF/MCS.FOI.MSGToPDF.csproj, MCS.FOI.S3FileConversion/MCS.FOI.MSGToPDF/MSGFileProcessor.cs
Reverts bcgov/foi-docreviewer#576
=> Revert "fix issue with special characters in href"

web/src/components/FOI/Home/DocumentSelector.scss, web/src/components/FOI/Home/Redlining.js
fix incompatible files missing from redline zip
add reuqest number to tab title
make max font size for redaction 9pt
=> change hex code for left panel selected items

web/src/components/FOI/Home/Redlining.js
Fix for single file - No stitching scenario
=> Fix for single file view- No stitching scenario

api/reviewer_api/resources/foiflowmasterdata.py, web/src/components/FOI/Home/Redlining.js, web/src/components/FOI/Home/utils.js
=> Dev st 4699

api/reviewer_api/resources/redaction.py, api/reviewer_api/services/annotationservice.py
Reverts bcgov/foi-docreviewer#619
=> Revert "add timestamp for debugging"

web/src/components/FOI/Home/DocumentSelector.tsx
apply different expand all node list depend on organize by
=> small bug fix

web/src/components/FOI/App.scss, web/src/components/FOI/Home/DocumentSelector.tsx
fix wrong logic in scrolling handler
=> fix scrolling bug when adding annotation

MCS.FOI.S3FileConversion/MCS.FOI.MSGToPDF/MSGFileProcessor.cs
fix msg type attachments missing from attachment list
=> fix issue with nested msg attachments

api/reviewer_api/resources/document.py, api/reviewer_api/services/documentservice.py, web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/LayerDropdown.tsx
Related to PR -> https://github.com/bcgov/foi-flow/pull/4900
this PR covers all validations for oipc layer activation (scenario 1 from ticket 4169 + all of ticket 4695)
=> Ticket 4695 + 4169 (Scenario 1). Validation of OIPC Review Layer 

computingservices/DedupeServices/services/s3documentservice.py
Reverts bcgov/foi-docreviewer#673
=> Revert "Fix for error related to Author"

computingservices/DedupeServices/services/s3documentservice.py
Reverts bcgov/foi-docreviewer#670
=> Revert "fix to dedupe: pdf with comments"

web/src/components/FOI/Home/Redlining.js
Reverts bcgov/foi-docreviewer#689
=> Revert "#4680 update saveRedlineDocument"

web/src/components/FOI/Home/Redlining.js
=> Incompatible file issue fix

web/src/components/FOI/Home/DocumentSelector.tsx, web/src/components/FOI/Home/Home.js, web/src/components/FOI/Home/utils.js
Sorting:
1. attachments following parent
2. sort by modified date for files in the same level
=> PR to docreviewer dev - update sorting

.github/workflows/documentservice-cd.yml, .github/workflows/documentservice-ci.yml, api/reviewer_api/schemas/finalpackage.py, api/reviewer_api/schemas/redline.py, api/reviewer_api/services/radactionservice.py, computingservices/DocumentServices/rstreamio/message/schemas/redactionsummary.py, computingservices/DocumentServices/services/dts/redactionsummary.py, computingservices/DocumentServices/services/redactionsummaryservice.py, computingservices/DocumentServices/services/zippingservice.py, web/src/components/FOI/Home/Redlining.js
Workflow updates and minor fixes
=> Workflow updates and minor fixes

web/src/components/FOI/Home/utils.js
=> update filename sorting - handle lower/upper case

api/reviewer_api/services/documentservice.py, web/src/components/FOI/Home/utils.js
tooltip in doc selector display last modified of attachment
(was showing last modified of parent)
=> tooltip in doc selector display last modified of attachment

computingservices/ZippingServices/models/zipperproducermessage.py
-Assign default values for parameters .
=> Changes to fix the exception on harms flow.

api/reviewer_api/models/AnnotationSections.py, api/reviewer_api/models/Annotations.py
fix for annotation section capture exception + redaction summary display in foi.
=> Dev st 2963

computingservices/DocumentServices/rstreamio/reader/documentservicestreamreader.py
merging directly as it is just to remove print statements inside While loop
=> removed print statements

api/dockerfile
Reverts bcgov/foi-docreviewer#831
=> Revert "353 - Update apt-get in Dockerfile"

web/src/components/FOI/Home/Redlining.js
FOIPPA Section Exceeds Redaction Box - Cut Off in Response Package
=> Fix for FOIPPA Section Exceeds Redaction Box - Cut Off in Response Package

web/src/components/FOI/Home/Redlining.js
Reverts bcgov/foi-docreviewer#840
=> Revert "FOIMOD-2959 - Fix for FOIPPA Section Exceeds Redaction Box - Cut Off in Response Package"

web/src/components/FOI/Home/Redlining.js
FOIMOD-2959- Fixed section cut off issue & fixed showing free hand annotations on response package occurring due to the fix of section cutoff issue.
=> FOIMOD-2959-Section cut off fix & other related fixes on response pkg

web/src/components/FOI/Home/Redlining.js
FOIMOD-2959-Fixed fillable pdf data loss issue introduced after fixing section cutoff.
=> FOIMOD-2959:Fixed fillable pdf data loss issue after fixing section cutoff issue

web/src/components/FOI/Home/Redlining.js, web/src/components/FOI/Home/utils.js
PR to dev for bug fix for FOIMOD-2985: conflicts between watermark & removepages
=> PR to dev for bug fix for FOIMOD-2985

web/src/components/FOI/Home/Redlining.js
FOIMOD-2985 bug fix: pagemapping did not include NR/dup pages
=> FOIMOD-2985 bug fix: pagemapping did not include NR/dup pages

.github/workflows/zap-scan.yml
FOIMOD-3026: Fix ZAP Scan issue and upgarde libraries: Node.js 16 actions are deprecated
=> FOIMOD-3026: Fix ZAP Scan issue and upgarde libraries: Node.js 16 actions are deprecated

web/src/components/FOI/Home/Home.js
Previous logic was not applying / validating oipclayer as a the currentLayer correctly. Fixed in this PR.
=> Ticket 2995. Adjustment / Bug Fix

api/reviewer_api/models/Annotations.py, api/reviewer_api/services/documentpageflagservice.py, api/reviewer_api/services/radactionservice.py, web/src/components/FOI/Home/Home.js
Reverts bcgov/foi-docreviewer#816
This tickets code/logic is now covered in branch test-rook-MD-4908-refactor and essentially moved from BE to FE
=> Revert "Ticket 2889. Adjust pageflag logic to apply appropriate pageflag based on redactions present"

web/src/components/FOI/Home/Redlining.js
=> FOIMOD-3062 Bug fix

web/src/components/FOI/Home/Redlining.js
=> Revert changes for FOIMOD-3062

web/src/components/FOI/Home/Redlining.js
Handle the case that one page can have two flags:  Consult flag + Another flag
=> Ignore consult flag when generate redline FOIMOD-3062

web/src/components/FOI/Home/Redlining.js
Description:
FOIPPA Section Exceeds Redaction Box - Cut Off in Response Package  : 
Cherry picked commits & merging to test-rook from dev-marshal
=> FOIMOD-2959 : FOIPPA Section Exceeds Redaction Box - Cut Off in Response Package 

computingservices/DocumentServices/rstreamio/message/schemas/redactionsummary.py, computingservices/DocumentServices/rstreamio/reader/documentservicestreamreader.py, computingservices/DocumentServices/services/dts/redactionsummary.py, computingservices/DocumentServices/services/redactionsummaryservice.py, computingservices/DocumentServices/services/zippingservice.py
Unit Testing [ministry (EDU & LDB)] -> Single & Multiple divisions & file, Incompatible, Edits
1. Create redline 
2. Create response package
3. Create oipc redline
4. Create oipc redline review
=> Changes to avoid data normalization using replace function.

api/reviewer_api/resources/document.py, web/src/components/FOI/Home/utils.js
Fixes for F.E multiple pageflags assignment & local testing code removed
=> Fixes for F.E multiple pageflag assignment & local testing code removed

api/reviewer_api/models/DocumentPageflags.py, api/reviewer_api/resources/documentpageflag.py, api/reviewer_api/services/documentpageflagservice.py, api/reviewer_api/services/radactionservice.py, web/src/components/FOI/Home/ConsultModal.tsx, web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/Home.js, web/src/components/FOI/Home/Redlining.js, web/src/components/FOI/Home/utils.js
Updated pageflag api to bring the updated pageflag field from db & update it in F.E rather than looping in F.E & assigning the flags.
=> Update on Pageflag API

web/src/components/FOI/Home/Redlining.js
avoid calling scroll left panel function on add redaction
=> change mouse handler to detect movement to

web/src/components/FOI/Home/Redlining.js
Unit Testing:
1. Create request
2. State transition till Records Review
3. Upload same record under multiple divisions and generate redline with "NR & Duplicate selected"
4. Upload same record under multiple divisions and generate redline without  "NR & Duplicate selected"
=> Changes to ignore duplicates for summary generation.

api/reviewer_api/models/DocumentPageflagHistory.py, api/reviewer_api/models/Keywords.py
Unit Testing
========
- Create new request
- State transition till records review
- Apply redactions and page flags
=> Changes to close the session.

api/reviewer_api/resources/document.py, api/reviewer_api/services/documentservice.py, web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/MCFPersonal.js
1. removed debugging code
2. added missing trackingid comparing
3. fixed disable edit tags condition
4. fixed ministry users could not update division for cfd personal
=> Bug fixes for FOIMOD-3044

web/src/components/FOI/Home/CreateResponsePDF/useSaveRedlineForSignOff.js, web/src/components/FOI/Home/Redlining.js
1. Removed comment out code
2. Bug fix: fix merge issues
=> Bug fix: fix merge issues

web/src/components/FOI/Home/DocumentSelector.tsx
FOIMOD-3300 - Release 10.0 Observations- Fix for Observation # 4 - Filter Records fix for CFD
=> FOIMOD-3300 - Fix Observation # 4 - Filter Records fix for CFD

web/src/components/FOI/Home/CustomTreeView.tsx, web/src/components/FOI/Home/DocumentSelector.tsx
FOIMOD-3300 -Fix for Observation # 3 - Left Hand Pane Not Expanding
=> FOIMOD-3300 -Fix for Observation # 3 - Left Hand Pane Not Expanding

api/reviewer_api/resources/redaction.py
Reverts bcgov/foi-docreviewer#1063
=> Revert "increase api response time to test timeout"

web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/DocumentSelector.scss
1. Fix observation 2 in FOIMOD-3044
2. Bug fix: error when click update tag button without change anything
=> 1. Fix observation 2 in FOIMOD-3044 2. Bug fix: error when click update tag button without change anything

web/src/components/FOI/Home/MCFPersonal.js
Fix observation #7 in FOIMOD-2976
=> Fix observation #7 in FOIMOD-2976

computingservices/DocumentServices/services/dts/redactionsummary.py
Fix observation 15 in FOIMOD-3300
=> Fix observation 15 in FOIMOD-3300

api/reviewer_api/models/AnnotationSections.py, api/reviewer_api/resources/redaction.py, api/reviewer_api/services/annotationservice.py
[FOIMOD-2479]
- Add function to combine document data and document page flag data to extract PageCount and Consultation flag data
=> [FOIMOD-2479] Add fetch func for PageCount/Consultation data 

web/src/components/FOI/Home/ContextMenu.tsx, web/src/components/FOI/Home/utils.js
Fix observation 27 in FOIMOD-3300
Fix observation 5 in FOIMOD-3044
=> Fix observations in FOIMOD-3300 and FOIMOD-3044

api/reviewer_api/services/documentservice.py, web/src/apiManager/services/docReviewerService.tsx, web/src/components/FOI/Home/Home.js, web/src/components/FOI/Home/utils.js
Fix observation #33 & 35 in FOIMOD-3300
=> Fix observation #33 & 35 in FOIMOD-3300

computingservices/DocumentServices/services/dts/redactionsummary.py
1. update cfd response summary
2. remove debugging code
=> 1. update cfd response summary 2. remove debugging code

web/src/components/FOI/Home/Redlining.js
Translucent redline box - FOIMOD-599
=> Translucent redline box - FOIMOD-599

web/src/components/FOI/Home/Redlining.js
Fix observation #1 in FOIMOD-599
=> Fix observation #1 in FOIMOD-599

api/reviewer_api/schemas/finalpackage.py, web/src/components/FOI/Home/CreateResponsePDF/CreateResponsePDF.js, web/src/components/FOI/Home/CreateResponsePDF/useSaveResponsePackage.js, web/src/components/FOI/Home/Redlining.js
Test marshal -  Feature not working due to Merge issues : resolved
=> FOIMOD-3073- Fees - Remaining Balance Check- Merge issues solved

api/reviewer_api/resources/redaction.py, api/reviewer_api/schemas/finalpackage.py, api/reviewer_api/schemas/redline.py, api/reviewer_api/services/radactionservice.py, computingservices/DocumentServices/rstreamio/message/schemas/redactionsummary.py, computingservices/DocumentServices/services/dts/redactionsummary.py, computingservices/DocumentServices/services/redactionsummaryservice.py, computingservices/DocumentServices/services/zippingservice.py, web/src/components/FOI/Home/CreateResponsePDF/useSaveRedlineForSignOff.js, web/src/components/FOI/Home/CreateResponsePDF/useSaveResponsePackage.js
Fix for Blank Response package Summaries getting created for CFD General Requests
=> FOIMOD-3431-Blank Response package Summaries getting created for CFD General Requests

web/src/components/FOI/Home/CreateResponsePDF/useSaveRedlineForSignOff.js
Reverts bcgov/foi-docreviewer#1170
=> Revert "Page Rotation fix for OIPC Redline S.14"

computingservices/DocumentServices/services/dts/redactionsummary.py
Reverts bcgov/foi-docreviewer#1139
=> Revert "3350 - Remove NR and duplicate from summary"

web/src/components/FOI/Home/CreateResponsePDF/useSaveRedlineForSignOff.js
Fix observation 1 in FOIMOD-3476
=> bug fix - missing page stamps - FOIMOD-3476

computingservices/ZippingServices/models/redlineresponsenotificationmessage.py, computingservices/ZippingServices/models/zipperproducermessage.py
Fixes for Harms download & Redline notification issues.
=> FOIMOD-3073-Fees - Remaining Balance Check

web/src/components/FOI/Home/Redlining.js
Reverts bcgov/foi-docreviewer#1205
=> Revert "3423 - Add filename to error toast"

web/src/apiManager/services/docReviewerService.tsx, web/src/helper/helper.ts
Reverts bcgov/foi-docreviewer#1195
=> Revert "3423 - Create errorToast for docReviewerService errors"

api/reviewer_api/schemas/finalpackage.py, api/reviewer_api/services/radactionservice.py, computingservices/DocumentServices/rstreamio/message/schemas/redactionsummary.py, computingservices/ZippingServices/services/zipperservice.py
Fixes to to small merge errors which created duplicate code of variables and functions.
=> Ticket 2646 (CONULTS): Merge fixes (when test-marshal was merged to main)

api/reviewer_api/models/DocumentAttributes.py, api/reviewer_api/services/documentservice.py
marked isactive in document attributes table
=> add defensive logic for multiple rows

computingservices/OpenInfoServices/lib/awslib/s3.go, computingservices/OpenInfoServices/main.go, computingservices/OpenInfoServices/services/messagehandler.go
1. set content type for html files 
2. correct the path for publishing files
=> 1. set content type for html files 2. correct the path for publishing files

computingservices/OpenInfoServices/lib/db/dbservices.go, computingservices/OpenInfoServices/lib/http/http.go, computingservices/OpenInfoServices/main.go
1. update debugging code
2. http client won't verify openshift tls certs
=> 1. update debugging code 2. http client won't verify openshift tls certs

computingservices/OpenInfoServices/lib/awslib/s3.go, computingservices/OpenInfoServices/services/messagehandler.go
bug fix: set content type header for html file created
=> set content type header for html file created

computingservices/OpenInfoServices/lib/awslib/s3.go
set content type for word, pdf and excel files for crawler
=> set content type for word, pdf and excel files for crawler

api/reviewer_api/resources/documentpageflag.py
- fixed search for non advanced search
- addressed kyles observations in ticket 3160
- adjusted queue for oi team to show correct page count
=> Release 14.0 (OpenInfo): Bug Fixes ->  Ticket 3160 and Ticket 3328 Observation fixes)

api/reviewer_api/models/Annotations.py, web/src/components/FOI/Home/DocumentSelector.tsx
=> optimize annotations query

web/src/components/FOI/Home/CustomTreeView.tsx, web/src/components/FOI/Home/DocumentSelector.tsx
Observation #2 : Fix for - When using the ‘Phase’ filter, sometimes the Completion % does not accurately reflect the completion percentage of the phase.
Observation #3: Fix - make sure these different types of page flags are always displayed in the same order.
=> FOIMOD-3566- Fixed observations

computingservices/DocumentServices/services/dts/redactionsummary.py, computingservices/ZippingServices/services/notificationservice.py, web/src/components/FOI/Home/CreateResponsePDF/useSaveResponsePackage.js
**Fixed : Observations #1 - #4 :**
#1:Response Package Summary of Redaction documents should not show the consultees.
#2: Page numbers in the Response Package Summary of Redactions should show the page numbers on the Response Package pdf. 
#3:When phased Response Packages are created, the notification for it is not working. 
#4: Unable to produce a non-phase Response Package.
=> FOIMOD-3568- observation fixes

api/reviewer_api/resources/foiflowmasterdata.py, computingservices/ZippingServices/services/notificationservice.py, web/src/components/FOI/Home/CreateResponsePDF/useSaveRedlineForSignOff.js
Ticket 3762 - Observation 1
Ticket 3567 - Observation 1 and 2
=> Release 17.0: Observation Fixes Part 2

api/reviewer_api/models/AnnotationSections.py
This is just for test and will revert the code
=> JUST FOR TEST - Optimized fetching for redacted section data

web/src/services/UserService.js
This PR fixes multiple Keycloak initializations by introducing a singleton pattern using keycloakInitialized and keycloakInitPromise.
=> [FOIMOD-3811] : Prevent multiple Keycloak initializations

web/src/components/FOI/Home/CreateResponsePDF/useSaveRedlineForSignOff.js
Reverts bcgov/foi-docreviewer#1351
=> Revert "Fixed FOIMOD-3851, issue in redline annotation"

.github/workflows/openinfoservice-cd.yml, computingservices/OpenInfoServices/.sampleenv, computingservices/OpenInfoServices/config/config.go, computingservices/OpenInfoServices/lib/awslib/s3.go, computingservices/OpenInfoServices/main.go, computingservices/OpenInfoServices/services/messagehandler.go, docker-compose.yml, openshift/templates/openinfoservice/openinfoservice-deploy.yaml, sample.env
Move elasticsearch supported mimetypes to env
=> Move elasticsearch supported mimetypes to env

computingservices/PDFStitchServices/services/pdfstitchjob.py, computingservices/ZippingServices/services/zipperdboperations.py
This pull request introduces changes to handle the `attributes` field more flexibly based on the `category` of the message.
=> Release 17.0 (Phased Release): Bug fixes

.github/workflows/api-cd.yml
=> Update Doc Reviewier AI Github Action

openshift/templates/documentextraction/push-to-queue/queue-documents.py
- Fetching incompatible files removed from document extraction
- Commit from Abin in test-rook - code fix for cronjob error on code for test-rook
=> FOIMOD-4024 - Fetching incompatible files removed from document extraction

web/src/components/FOI/Home/Redlining.js
=> Ticket 4035: Added logic for Areanntsrendered check to only run once stitching is completed as well.

.github/workflows/compressionservice-cd.yml, .github/workflows/ocrservice-cd.yml
Removing env hardcode from naming convention, hardcoding oc env.
=> Update OCR and Compression to include largefiles
